-- ════════════════════════════════════════════════════════════════════════════
-- schema.sql — the live public schema of Supabase project nitchusgmixyrbqswdhe,
-- as at 2026-10-05, BEFORE migration 001_push_notifications.sql was applied.
--
-- Generated by supabase/dump-schema.sql (SQL Editor → run → download). This is a
-- snapshot for reference, not a migration — do not run it against a live database.
-- Regenerate it after any schema change so this file stays honest.
--
-- This project is SHARED with the cooking planner. The cook_session, grocery_state,
-- recipe_preferences, schedule and user_pairings tables and their policies belong to
-- that app and are reference only — study-app work must not modify them.
--
-- Study app tables: progress (reading), write_progress (writing), user_settings,
-- notes, synonyms.
-- ════════════════════════════════════════════════════════════════════════════

-- extension: pg_stat_statements 1.11 (schema: extensions)
-- extension: pgcrypto 1.3 (schema: extensions)
-- extension: plpgsql 1.0 (schema: pg_catalog)
-- extension: supabase_vault 0.3.1 (schema: vault)
-- extension: uuid-ossp 1.1 (schema: extensions)
-- NOTE: pg_cron and pg_net are NOT installed. Migration 001 requires both.

create table cook_session (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  meal1_id text not null,
  meal2_id text not null,
  current_step integer not null default 0,
  total_steps integer not null default 0,
  week_number integer not null default 1,
  completed boolean not null default false,
  updated_at timestamp with time zone default now()
);
create table grocery_state (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  checked_items jsonb not null default '{}'::jsonb,
  servings jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone default now()
);
create table notes (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  item_id text not null,
  description text,
  notes text,
  updated_at timestamp with time zone default now()
);
create table progress (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  item_id text not null,
  level integer not null default 0,
  updated_at timestamp with time zone default now(),
  last_quizzed timestamp with time zone,
  streak integer not null default 0
);
create table recipe_preferences (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  recipe_id text not null,
  auto_pairing_eligible boolean,
  rating integer,
  favourite boolean not null default false,
  notes text,
  updated_at timestamp with time zone default now()
);
create table schedule (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  cook_day integer not null default 6,
  current_week integer not null default 1,
  last_cooked_at timestamp with time zone,
  updated_at timestamp with time zone default now()
);
create table synonyms (
  id uuid not null default uuid_generate_v4(),
  user_id uuid not null,
  item_id text not null,
  synonym text not null,
  created_at timestamp with time zone default now()
);
create table user_pairings (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  week_number integer not null,
  meal_a_id text not null,
  meal_b_id text not null,
  created_at timestamp with time zone default now()
);
create table user_settings (
  user_id uuid not null,
  streak integer default 0,
  last_study_date date,
  updated_at timestamp with time zone default now(),
  unlocked_levels jsonb default '[1]'::jsonb,
  configuration jsonb default '{}'::jsonb
);
create table write_progress (
  user_id uuid not null,
  item_id text not null,
  level integer not null default 0,
  last_quizzed timestamp with time zone,
  updated_at timestamp with time zone not null default now(),
  streak integer not null default 0
);

alter table cook_session enable row level security;
alter table grocery_state enable row level security;
alter table notes enable row level security;
alter table progress enable row level security;
alter table recipe_preferences enable row level security;
alter table schedule enable row level security;
alter table synonyms enable row level security;
alter table user_pairings enable row level security;
alter table user_settings enable row level security;
alter table write_progress enable row level security;

alter table cook_session add constraint cook_session_pkey PRIMARY KEY (id);
alter table cook_session add constraint cook_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table cook_session add constraint cook_session_user_id_key UNIQUE (user_id);
alter table grocery_state add constraint grocery_state_pkey PRIMARY KEY (id);
alter table grocery_state add constraint grocery_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table grocery_state add constraint grocery_state_user_id_key UNIQUE (user_id);
alter table notes add constraint notes_pkey PRIMARY KEY (id);
alter table notes add constraint notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table notes add constraint notes_user_id_item_id_key UNIQUE (user_id, item_id);
alter table progress add constraint progress_level_check CHECK (((level >= 0) AND (level <= 6)));
alter table progress add constraint progress_pkey PRIMARY KEY (id);
alter table progress add constraint progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table progress add constraint progress_user_id_item_id_key UNIQUE (user_id, item_id);
alter table recipe_preferences add constraint recipe_preferences_pkey PRIMARY KEY (id);
alter table recipe_preferences add constraint recipe_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table recipe_preferences add constraint recipe_preferences_user_id_recipe_id_key UNIQUE (user_id, recipe_id);
alter table schedule add constraint schedule_pkey PRIMARY KEY (id);
alter table schedule add constraint schedule_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table schedule add constraint schedule_user_id_key UNIQUE (user_id);
alter table synonyms add constraint synonyms_pkey PRIMARY KEY (id);
alter table synonyms add constraint synonyms_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table synonyms add constraint synonyms_user_id_item_id_synonym_key UNIQUE (user_id, item_id, synonym);
alter table user_pairings add constraint user_pairings_pkey PRIMARY KEY (id);
alter table user_pairings add constraint user_pairings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table user_pairings add constraint user_pairings_user_id_week_number_key UNIQUE (user_id, week_number);
alter table user_settings add constraint user_settings_pkey PRIMARY KEY (user_id);
alter table user_settings add constraint user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table write_progress add constraint write_progress_level_check CHECK (((level >= 0) AND (level <= 6)));
alter table write_progress add constraint write_progress_pkey PRIMARY KEY (user_id, item_id);
alter table write_progress add constraint write_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX notes_user_id_idx ON public.notes USING btree (user_id);
CREATE INDEX progress_last_quizzed_idx ON public.progress USING btree (user_id, last_quizzed) WHERE (last_quizzed IS NOT NULL);
CREATE INDEX progress_user_id_idx ON public.progress USING btree (user_id);
CREATE INDEX synonyms_user_id_idx ON public.synonyms USING btree (user_id);
CREATE INDEX write_progress_last_quizzed_idx ON public.write_progress USING btree (user_id, last_quizzed);
CREATE INDEX write_progress_user_id_idx ON public.write_progress USING btree (user_id);

CREATE OR REPLACE FUNCTION public.force_read_level(p_item_id text, p_level integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO progress (user_id, item_id, level, streak, updated_at)
    VALUES (auth.uid(), p_item_id, p_level, 0, now())
    ON CONFLICT (user_id, item_id)
    DO UPDATE SET level = p_level, streak = 0, updated_at = now();
    RETURN p_level;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.force_write_level(p_item_id text, p_level integer, p_user_id uuid)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO write_progress (user_id, item_id, level, streak, updated_at)
    VALUES (p_user_id, p_item_id, p_level, 0, now())
    ON CONFLICT (user_id, item_id)
    DO UPDATE SET level = EXCLUDED.level, streak = 0, updated_at = now();
    RETURN p_level;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_note(p_item_id text, p_description text, p_notes text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into notes (user_id, item_id, description, notes, updated_at)
  values (auth.uid(), p_item_id, p_description, p_notes, now())
  on conflict (user_id, item_id)
  do update set description = p_description, notes = p_notes, updated_at = now();
end;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_progress(p_item_id text, p_level integer, p_threshold integer DEFAULT 0)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_threshold int := COALESCE(p_threshold, 0);
    v_current   int;
    v_streak    int;
    v_level     int;
    v_new_streak int;
BEGIN
    SELECT level, streak INTO v_current, v_streak
    FROM progress
    WHERE user_id = auth.uid() AND item_id = p_item_id;

    IF v_current IS NULL THEN
        v_current := 0;
        v_streak  := 0;
    END IF;

    IF v_threshold >= 2 AND p_level > v_current THEN
        v_new_streak := v_streak + 1;
        IF v_new_streak >= v_threshold THEN
            v_level := p_level;
            v_new_streak := 0;
        ELSE
            v_level := v_current;
        END IF;
    ELSIF p_level = v_current THEN
        v_level := p_level;
        v_new_streak := v_streak + 1;
    ELSE
        v_level := p_level;
        v_new_streak := 0;
    END IF;

    INSERT INTO progress (user_id, item_id, level, streak, updated_at)
    VALUES (auth.uid(), p_item_id, v_level, v_new_streak, now())
    ON CONFLICT (user_id, item_id)
    DO UPDATE SET
        level      = v_level,
        streak     = v_new_streak,
        updated_at = now();

    RETURN v_level;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_user_settings(p_streak integer, p_last_study_date date, p_unlocked_levels jsonb DEFAULT NULL::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  existing_levels jsonb;
  merged_levels jsonb;
begin
  select coalesce(unlocked_levels, '[]'::jsonb) into existing_levels
  from user_settings
  where user_id = auth.uid();

  existing_levels := coalesce(existing_levels, '[]'::jsonb);

  if p_unlocked_levels is null or p_unlocked_levels = '[]'::jsonb then
    merged_levels := case
      when existing_levels = '[]'::jsonb then '[1]'::jsonb
      else existing_levels
    end;
  elsif existing_levels = '[]'::jsonb then
    merged_levels := p_unlocked_levels;
  elsif jsonb_array_length(p_unlocked_levels) >= jsonb_array_length(existing_levels) then
    merged_levels := p_unlocked_levels;
  else
    merged_levels := existing_levels;
  end if;

  insert into user_settings (user_id, streak, last_study_date, unlocked_levels, updated_at)
  values (auth.uid(), p_streak, p_last_study_date, merged_levels, now())
  on conflict (user_id)
  do update set
    streak = p_streak,
    last_study_date = p_last_study_date,
    unlocked_levels = merged_levels,
    updated_at = now();
end;
$function$
;

-- NOTE: two overloads of upsert_user_settings exist. The page calls this 4-arg one
-- (p_streak, p_last_study_date, p_configuration), relying on p_unlocked_levels
-- defaulting to NULL. Its indentation is mangled in the live database; reproduced here
-- as-is rather than tidied, so this file matches what is actually deployed.
CREATE OR REPLACE FUNCTION public.upsert_user_settings(p_streak integer, p_last_study_date date, p_unlocked_levels jsonb DEFAULT NULL::jsonb, p_configuration jsonb DEFAULT NULL::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
        declare
          existing_levels jsonb;
            merged_levels jsonb;
            begin
              select coalesce(unlocked_levels, '[]'::jsonb) into existing_levels
                from user_settings
                  where user_id = auth.uid();

                    existing_levels := coalesce(existing_levels, '[]'::jsonb);

                      if p_unlocked_levels is null or p_unlocked_levels = '[]'::jsonb then
                          merged_levels := case
                                when existing_levels = '[]'::jsonb then '[1]'::jsonb
                                      else existing_levels
                                          end;
                                            elsif existing_levels = '[]'::jsonb then
                                                merged_levels := p_unlocked_levels;
                                                  elsif jsonb_array_length(p_unlocked_levels) >= jsonb_array_length(existing_levels) then
                                                      merged_levels := p_unlocked_levels;
                                                        else
                                                            merged_levels := existing_levels;
                                                              end if;

                                                                insert into user_settings (user_id, streak, last_study_date, unlocked_levels, configuration, updated_at)
                                                                  values (auth.uid(), p_streak, p_last_study_date, merged_levels,
                                                                      coalesce(p_configuration, '{}'::jsonb),
                                                                          now())
                                                                            on conflict (user_id) do update set
                                                                                streak = p_streak,
                                                                                    last_study_date = p_last_study_date,
                                                                                        unlocked_levels = merged_levels,
                                                                                            configuration = coalesce(p_configuration, user_settings.configuration),
                                                                                                updated_at = now();
                                                                                                end;
                                                                                                $function$
;

CREATE OR REPLACE FUNCTION public.upsert_write_progress(p_item_id text, p_level integer, p_last_quizzed timestamp with time zone, p_user_id uuid, p_threshold integer DEFAULT 0)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_threshold int := COALESCE(p_threshold, 0);
    v_current   int;
    v_streak    int;
    v_level     int;   -- level we will actually commit
    v_new_streak int;
BEGIN
    SELECT level, streak INTO v_current, v_streak
    FROM write_progress
    WHERE user_id = p_user_id AND item_id = p_item_id;

    IF v_current IS NULL THEN
        v_current := 0;
        v_streak  := 0;
    END IF;

    IF v_threshold >= 2 AND p_level > v_current THEN
        -- Gated rung: hold here and count up, release only at threshold.
        v_new_streak := v_streak + 1;
        IF v_new_streak >= v_threshold THEN
            v_level := p_level;      -- promote (rung change)
            v_new_streak := 0;       -- rung changed -> reset
        ELSE
            v_level := v_current;    -- stay put (same rung -> streak stands)
        END IF;
    ELSIF p_level = v_current THEN
        -- Same rung, not gated: generic increment.
        v_level := p_level;
        v_new_streak := v_streak + 1;
    ELSE
        -- Any other rung change (promotion elsewhere, or a lapse/drop): reset.
        v_level := p_level;
        v_new_streak := 0;
    END IF;

    INSERT INTO write_progress (user_id, item_id, level, last_quizzed, streak, updated_at)
    VALUES (p_user_id, p_item_id, v_level, p_last_quizzed, v_new_streak, now())
    ON CONFLICT (user_id, item_id)
    DO UPDATE SET
        level        = EXCLUDED.level,
        last_quizzed = EXCLUDED.last_quizzed,
        streak       = EXCLUDED.streak,
        updated_at   = now();

    RETURN v_level;
END;
$function$
;

create policy cook_session_insert on cook_session for insert to public with check ((auth.uid() = user_id));
create policy cook_session_select on cook_session for select to public using ((auth.uid() = user_id));
create policy cook_session_update on cook_session for update to public using ((auth.uid() = user_id));
create policy grocery_state_insert on grocery_state for insert to public with check ((auth.uid() = user_id));
create policy grocery_state_select on grocery_state for select to public using ((auth.uid() = user_id));
create policy grocery_state_update on grocery_state for update to public using ((auth.uid() = user_id));
create policy "Users can delete own notes" on notes for delete to public using ((auth.uid() = user_id));
create policy "Users can insert own notes" on notes for insert to public with check ((auth.uid() = user_id));
create policy "Users can update own notes" on notes for update to public using ((auth.uid() = user_id));
create policy "Users can view own notes" on notes for select to public using ((auth.uid() = user_id));
create policy "Users can delete own progress" on progress for delete to public using ((auth.uid() = user_id));
create policy "Users can insert own progress" on progress for insert to public with check ((auth.uid() = user_id));
create policy "Users can update own progress" on progress for update to public using ((auth.uid() = user_id));
create policy "Users can view own progress" on progress for select to public using ((auth.uid() = user_id));
create policy recipe_preferences_delete on recipe_preferences for delete to authenticated using ((auth.uid() = user_id));
create policy recipe_preferences_insert on recipe_preferences for insert to authenticated with check ((auth.uid() = user_id));
create policy recipe_preferences_select on recipe_preferences for select to authenticated using ((auth.uid() = user_id));
create policy recipe_preferences_update on recipe_preferences for update to authenticated using ((auth.uid() = user_id));
create policy schedule_insert on schedule for insert to public with check ((auth.uid() = user_id));
create policy schedule_select on schedule for select to public using ((auth.uid() = user_id));
create policy schedule_update on schedule for update to public using ((auth.uid() = user_id));
create policy "Users can delete own synonyms" on synonyms for delete to public using ((auth.uid() = user_id));
create policy "Users can insert own synonyms" on synonyms for insert to public with check ((auth.uid() = user_id));
create policy "Users can update own synonyms" on synonyms for update to public using ((auth.uid() = user_id));
create policy "Users can view own synonyms" on synonyms for select to public using ((auth.uid() = user_id));
create policy user_pairings_delete on user_pairings for delete to public using ((auth.uid() = user_id));
create policy user_pairings_insert on user_pairings for insert to public with check ((auth.uid() = user_id));
create policy user_pairings_select on user_pairings for select to public using ((auth.uid() = user_id));
create policy user_pairings_update on user_pairings for update to public using ((auth.uid() = user_id));
create policy "Users can insert own settings" on user_settings for insert to public with check ((auth.uid() = user_id));
create policy "Users can update own settings" on user_settings for update to public using ((auth.uid() = user_id));
create policy "Users can view own settings" on user_settings for select to public using ((auth.uid() = user_id));
create policy "Users can delete own write_progress" on write_progress for delete to public using ((auth.uid() = user_id));
create policy "Users can insert own write_progress" on write_progress for insert to public with check ((auth.uid() = user_id));
create policy "Users can read own write_progress" on write_progress for select to public using ((auth.uid() = user_id));
create policy "Users can update own write_progress" on write_progress for update to public using ((auth.uid() = user_id));
